name: Create Tag and Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag in format <Major>.<Minor>.<Patch>'
        required: true
        type: string
      isPreRelease:
        description: 'is that a pre-Release?'
        required: false
        default: false
        type: boolean
  
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${{ github.event.inputs.tag }}"
          tag_exists_error: true
          message: "${{ github.event.inputs.tag }} Release"
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        replacesArtifacts: true
        tag: "${{ github.event.inputs.tag }}"
        prerelease: "${{ github.event.inputs.isPreRelease }}"
