name: Create Tag and Release
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag in format <Major>.<Minor>.<Patch>'
        required: true
        type: string
      isPreRelease:
        description: 'is that a pre-Release?'
        required: false
        default: false
        type: boolean
  
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
      with:
        replacesArtifacts: true
        tag: "${{ github.event.inputs.tag }}"
        prerelease: "${{ github.event.inputs.isPreRelease }}"
