name: Create Tag
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag in format <Major>.<Minor>.<Patch>'
        required: true
        type: string
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "${{ github.event.inputs.tag }}"
          tag_exists_error: false
          message: "${{ github.event.inputs.tag }} Release"
